package tp8.gui;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Formulario extends javax.swing.JFrame {

    private JTextField txtNombres, txtApellidos, txtEdad, txtDepartamento;

    public Formulario() {
        // Configuración del formulario
        setTitle("Formulario de Información");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(null);

        // Componentes del formulario
        JLabel lblNombres = new JLabel("Nombres:");
        lblNombres.setBounds(20, 20, 80, 25);
        add(lblNombres);

        txtNombres = new JTextField();
        txtNombres.setBounds(120, 20, 200, 25);
        add(txtNombres);

        JLabel lblApellidos = new JLabel("Apellidos:");
        lblApellidos.setBounds(20, 60, 80, 25);
        add(lblApellidos);

        txtApellidos = new JTextField();
        txtApellidos.setBounds(120, 60, 200, 25);
        add(txtApellidos);

        JLabel lblEdad = new JLabel("Edad:");
        lblEdad.setBounds(20, 100, 80, 25);
        add(lblEdad);

        txtEdad = new JTextField();
        txtEdad.setBounds(120, 100, 50, 25);
        add(txtEdad);

        JLabel lblDepartamento = new JLabel("Departamento:");
        lblDepartamento.setBounds(20, 140, 100, 25);
        add(lblDepartamento);

        txtDepartamento = new JTextField();
        txtDepartamento.setBounds(120, 140, 200, 25);
        add(txtDepartamento);

        JButton btnValidar = new JButton("Validar");
        btnValidar.setBounds(20, 180, 100, 25);
        btnValidar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                validarInformacion();
            }
        });
        add(btnValidar);

        JButton btnLimpiar = new JButton("Limpiar");
        btnLimpiar.setBounds(150, 180, 100, 25);
        btnLimpiar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                limpiarCampos();
            }
        });
        add(btnLimpiar);
    }

    private void validarInformacion() {
        String nombres = txtNombres.getText();
        String apellidos = txtApellidos.getText();
        String edad = txtEdad.getText();
        String departamento = txtDepartamento.getText();

        if (nombres.isEmpty() || apellidos.isEmpty() || edad.isEmpty() || departamento.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete toda la información.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String mensaje = String.format("Bienvenido %s %s, usted tiene %s años y vive en %s.", nombres, apellidos, edad, departamento);
            JOptionPane.showMessageDialog(this, mensaje, "Bienvenido", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void limpiarCampos() {
        txtNombres.setText("");
        txtApellidos.setText("");
        txtEdad.setText("");
        txtDepartamento.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
